routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'Admin'], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('header', 'HeaderController');
    Route::resource('feature', 'FeaturesController');
    Route::resource('pricing', 'PriceController');
    Route::resource('pricing-feature', 'PriceFeatureController');
});

app/Header.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Header extends Model
{
    public $timestamps = true;
}

app/Http/Controllers/Admin/HeaderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Header;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class HeaderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $headers = Header::latest()->get();
        return view('backend.header.index', compact('headers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.header.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request, [
           'title' => 'required|string',
           'description' => 'required|string'
       ]);

       $header = new Header();
       $header->title = $request->title;
       $header->description = $request->description;
       $header->save();

       Toastr::success('Data Successfully Saved :)', 'Success');
       return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $header = Header::findOrFail($id);
        return view('backend.header.show', compact('header'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $header = Header::findOrFail($id);
        return view('backend.header.edit', compact('header'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|string',
            'description' => 'required|string'
        ]);

        $header = Header::findOrFail($id);
        $header->title = $request->title;
        $header->description = $request->description;
        $header->save();

        Toastr::success('Data Successfully Updated :)', 'Success');
        return redirect(route('header.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $header = Header::findOrFail($id);
        $header->delete();

        Toastr::success('Data Successfully Deleted :)', 'Success');
        return back();
    }
}

resources/views/backend/header/create.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Header-Part')

@section('content-header')
    <h1>
        Create
        <small>Control Header Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Create
                        </h2>
                        <a href="{{ route('header.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                                <form class="form-horizontal" style="padding-right: 120px;" action="{{ route('header.store') }}" method="POST">
                                    @csrf
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="title">Title</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{ old('title') }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="description">Description</label>
                                        <div class="col-sm-10">
                                            <textarea rows="10" type="text" class="form-control" id="description" placeholder="Enter description" name="description">{{ old('description') }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <button type="submit" name="submit" class="btn btn-default">Submit</button>
                                        </div>
                                    </div>
                                </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/header/edit.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Header-Part')

@section('content-header')
    <h1>
        Edit
        <small>Control Header Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Edit
                        </h2>
                        <a href="{{ route('header.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" style="padding-right: 120px;" action="{{ route('header.update', $header->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="title">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{ $header->title }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="description">Description</label>
                                <div class="col-sm-10">
                                    <textarea rows="10" type="text" class="form-control" id="description" placeholder="Enter description" name="description">{{ $header->description}}</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" name="submit" class="btn btn-default">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/header/index.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Header-Part')

@section('content-header')
    <h1>
        Header Part
        <small>Control Header Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Header Section
                        </h2>
                        <a href="{{ route('header.create') }}" class="btn btn-default pull-right" style="margin-top: -25px;">Add New</a>
                    </div>
                    <div class="panel-body">
                        <table id="datatable" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($headers as $header)
                                    <tr>
                                        <td>{{ $header->title }}</td>
                                        <td>{{ Str::limit($header->description, 30) }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('header.edit', $header->id) }}" class="btn btn-info btn-sm">
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            <button onclick="deleteHeader({{ $header->id }})" class="btn btn-danger" type="button">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                            <form id="delete-form-{{ $header->id }}" action="{{ route('header.destroy', $header->id) }}" method="POST" style="display: none;">
                                                @csrf
                                                @method('DELETE')
                                            </form>

                                            <a href="{{ route('header.show', $header->id) }}" class="btn btn-primary btn-sm">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- Sweet Alert 2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8.3.0/dist/sweetalert2.all.min.js"></script>
    <!-- Sweet Alert 2 End -->
    <script type="text/javascript">
        function deleteHeader(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/backend/header/show.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Header-Part')

@section('content-header')
    <h1>
        Create
        <small>Control Header Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Show Header Content
                        </h2>
                        <a href="{{ route('header.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                        <h3>Title: {{ $header->title }}</h3>
                        <h5>Description: {{ $header->description }}</h5>
                        <a href="{{ route('header.edit', $header->id) }}" class="btn btn-primary">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection