routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'Admin'], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('header', 'HeaderController');
    Route::resource('feature', 'FeaturesController');
    Route::resource('pricing', 'PriceController');
    Route::resource('pricing-feature', 'PriceFeatureController');
});

resources/views/backend/pricing/create.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Pricing-Part')

@push('css')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('assets/backend/bower_components/select2/dist/css/select2.min.css') }}">
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background-color: #3c8dbc;
            border-color: #367fa9;
            padding: 1px 10px;
            color: #fff;
        }
    </style>
@endpush

@section('content-header')
    <h1>
        Create
        <small>Control Pricing Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Create Pricing
                        </h2>
                        <a href="{{ route('pricing.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                                <form class="form-horizontal" style="padding-right: 120px;" action="{{ route('pricing.store') }}" method="POST">
                                    @csrf
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="title">Title</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{ old('title') }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="feature">Features</label>
                                        <div class="col-sm-10 {{ $errors->has('features')? 'focused error':'' }}">
                                            <select class="form-control select2" name="features[]" id="feature" data-live-search="true" multiple="multiple" data-placeholder="Select a State"
                                                    style="width: 100%;">
                                                @foreach($features as $feature)
                                                    <option value="{{ $feature->id }}">{{ $feature->feature }}</option>
                                                @endforeach
                                            </select>
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="price">Price</label>
                                        <div class="col-sm-10">
                                            <input type="number" step="0.01" class="form-control" id="price" placeholder="Enter Price" name="price" value="{{ old('price') }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <button type="submit" name="submit" class="btn btn-default">Submit</button>
                                        </div>
                                    </div>
                                </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- Select2 -->
    <script src="{{ asset('assets/backend/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
    <script>
        //Initialize Select2 Elements
        $('.select2').select2()
    </script>
@endpush

resources/views/backend/pricing/edit.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Pricing-Part')

@push('css')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('assets/backend/bower_components/select2/dist/css/select2.min.css') }}">
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background-color: #3c8dbc;
            border-color: #367fa9;
            padding: 1px 10px;
            color: #fff;
        }
    </style>
@endpush

@section('content-header')
    <h1>
        Edit
        <small>Control Pricing Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Edit Pricing
                        </h2>
                        <a href="{{ route('pricing.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" style="padding-right: 120px;" action="{{ route('pricing.update', $price->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="title">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{ $price->title }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="feature">Features</label>
                                <div class="col-sm-10 {{ $errors->has('features')? 'focused error':'' }}">
                                    <select class="form-control select2" name="features[]" id="feature" data-live-search="true" multiple="multiple" data-placeholder="Select a State"
                                            style="width: 100%;">
                                        @foreach($features as $feature)
                                            <option
                                                @foreach($price->conditions as $priceFeature)
                                                    {{ $priceFeature->id == $feature->id ? 'selected':'' }}
                                                @endforeach
                                                value="{{ $feature->id }}">{{ $feature->feature }}</option>
                                        @endforeach
                                    </select>
                                </div>

                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="price">Price</label>
                                <div class="col-sm-10">
                                    <input type="number" step="0.01" class="form-control" id="price" placeholder="Enter Price" name="price" value="{{ $price->price }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" name="submit" class="btn btn-default">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- Select2 -->
    <script src="{{ asset('assets/backend/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
    <script>
        //Initialize Select2 Elements
        $('.select2').select2()
    </script>
@endpush

resources/views/backend/pricing/index.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Pricing-Part')

@section('content-header')
    <h1>
        Pricing Part
        <small>Control Pricing Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Pricing Section
                        </h2>
                        <a href="{{ route('pricing.create') }}" class="btn btn-default pull-right" style="margin-top: -25px;">Add New</a>
                        <a href="{{ route('pricing-feature.index') }}" class="btn btn-success pull-right" style="margin-top: -25px; margin-right: 10px;">Pricing Feature</a>
                    </div>
                    <div class="panel-body">
                        <table id="datatable" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Feature Count</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($prices as $price)
                                    <tr>
                                        <td>{{ $price->title }}</td>
                                        <td>{{ $price->price }}</td>
                                        <td>{{ $price->conditions->count() }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('pricing.edit', $price->id) }}" class="btn btn-info btn-sm">
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            <button onclick="deletePrice({{ $price->id }})" class="btn btn-danger" type="button">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                            <form id="delete-form-{{ $price->id }}" action="{{ route('pricing.destroy', $price->id) }}" method="POST" style="display: none;">
                                                @csrf
                                                @method('DELETE')
                                            </form>

                                            <a href="{{ route('pricing.show', $price->id) }}" class="btn btn-primary btn-sm">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Feature Count</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- Sweet Alert 2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8.3.0/dist/sweetalert2.all.min.js"></script>
    <!-- Sweet Alert 2 End -->
    <script type="text/javascript">
        function deletePrice(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/backend/pricing/show.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Pricing-Part')

@section('content-header')
    <h1>
        Show Pricing
        <small>Control Pricing Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Show Price Content
                        </h2>
                        <a href="{{ route('pricing.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                        <h3>Title: {{ $price->title }}</h3>
                        <h5>Price: {{ $price->price }}</h5>
                        <ol>
                            @foreach($price->conditions as $feature)
                                <li>{{ $feature->feature }}</li>
                            @endforeach
                        </ol>
                        <a href="{{ route('pricing.edit', $feature->id) }}" class="btn btn-primary">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection