routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'Admin'], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('header', 'HeaderController');
    Route::resource('feature', 'FeaturesController');
    Route::resource('pricing', 'PriceController');
    Route::resource('pricing-feature', 'PriceFeatureController');
});

resources/views/backend/pricing-feature/create.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Condition-Part')

@section('content-header')
    <h1>
        Create Condition
        <small>Control Pricing Condition Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Create Pricing Condition
                        </h2>
                        <a href="{{ route('pricing-feature.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                                <form class="form-horizontal" style="padding-right: 120px;" action="{{ route('pricing-feature.store') }}" method="POST">
                                    @csrf
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="title">Title</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{ old('title') }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <button type="submit" name="submit" class="btn btn-default">Submit</button>
                                        </div>
                                    </div>
                                </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pricing-feature/edit.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Condition-Part')

@section('content-header')
    <h1>
        Edit
        <small>Control Pricing Condition Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Edit Pricing Condition
                        </h2>
                        <a href="{{ route('pricing-feature.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" style="padding-right: 120px;" action="{{ route('pricing-feature.update', $feature->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="title">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{ $feature->feature }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" name="submit" class="btn btn-default">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pricing-feature/index.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Pricing-Part')

@section('content-header')
    <h1>
        Pricing Part
        <small>Control Pricing Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Pricing Section
                        </h2>
                        <a href="{{ route('pricing-feature.create') }}" class="btn btn-default pull-right" style="margin-top: -25px;">Add New</a>
                    </div>
                    <div class="panel-body">
                        <table id="datatable" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Price Count</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($features as $feature)
                                    <tr>
                                        <td>{{ Str::limit($feature->feature, 30) }}</td>
                                        <td>{{ $feature->price->count() }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('pricing-feature.edit', $feature->id) }}" class="btn btn-info btn-sm">
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            <button onclick="deleteCondition({{ $feature->id }})" class="btn btn-danger" type="button">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                            <form id="delete-form-{{ $feature->id }}" action="{{ route('pricing-feature.destroy', $feature->id) }}" method="POST" style="display: none;">
                                                @csrf
                                                @method('DELETE')
                                            </form>

                                            <a href="{{ route('pricing-feature.show', $feature->id) }}" class="btn btn-primary btn-sm">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Price Count</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- Sweet Alert 2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8.3.0/dist/sweetalert2.all.min.js"></script>
    <!-- Sweet Alert 2 End -->
    <script type="text/javascript">
        function deleteCondition(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/backend/pricing-feature/show.blade.php
@extends('backend.layouts.app')

@section('dashboard-title', 'Condition-Part')

@section('content-header')
    <h1>
        Show Pricing
        <small>Control Pricing Condition Part</small>
    </h1>
@endsection

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading" style="padding: 20px 20px;">
                        <h2 class="panel-title">
                            Show Price Condition Content
                        </h2>
                        <a href="{{ route('pricing-feature.index') }}" class="btn btn-danger pull-right" style="margin-top: -25px;">Back</a>
                    </div>
                    <div class="panel-body">
                        <h3>Title: {{ $feature->feature }}</h3>
                        <a href="{{ route('pricing-feature.edit', $feature->id) }}" class="btn btn-primary">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection